# Generated by Django 3.2.7 on 2021-10-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20210925_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='google_plus',
        ),
        migrations.AddField(
            model_name='business',
            name='linkedin',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Lien Compte Linkedin'),
        ),
    ]
