# Generated by Django 3.2.7 on 2021-10-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20211003_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, verbose_name='Question')),
                ('reponse', models.TextField(verbose_name='Réponse')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
            ],
        ),
    ]
