# Generated by Django 3.2.7 on 2021-10-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_remove_counter_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientservice',
            name='icon',
        ),
        migrations.AlterField(
            model_name='clientservice',
            name='name',
            field=models.CharField(max_length=150, verbose_name="titre de l'acomplissement"),
        ),
        migrations.AlterField(
            model_name='clientservice',
            name='sub_title',
            field=models.CharField(max_length=150, verbose_name="sous titre de l'acomplissement"),
        ),
    ]
