# Generated by Django 3.2.7 on 2022-02-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_partner_siteweb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='number',
            field=models.IntegerField(default=0, verbose_name='chiffre'),
        ),
    ]
