# Generated by Django 3.2.7 on 2022-02-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_alter_counter_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='sub_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Sous titre de la photo'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Grand titre de la photo'),
        ),
    ]
