# Generated by Django 3.2.7 on 2022-02-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_solution_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/solutions'),
        ),
    ]
