# Generated by Django 3.2.7 on 2022-02-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_solution_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='home_image',
            field=models.ImageField(blank=True, null=True, upload_to='icon'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='icon'),
        ),
    ]
